image: idotdigital/builder

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  DOCKER_IMAGE: idotdigital/eventsdb
  DOCKER_TAG: ${CI_COMMIT_SHA}

stages:
  - build
  - docker
  - release

.build_template: &build_definition
  stage: build
  before_script:
    - mkdir -p $GOPATH/bin
    - export PATH="$PATH:$HOME/go/bin"
    - go mod download
  script:
    - mkdir -p bin
    - make proto sqlc
    - go build -o bin/eventsdb-$GOOS-$GOARCH$FILE_EXTENSION cmd/server/main.go
  artifacts:
    paths:
      - bin/
    expire_in: 1 week

build_linux_amd64:
  <<: *build_definition
  variables:
    GOOS: linux
    GOARCH: amd64

build_linux_arm64:
  <<: *build_definition
  variables:
    GOOS: linux
    GOARCH: arm64

build_darwin_amd64:
  <<: *build_definition
  variables:
    GOOS: darwin
    GOARCH: amd64

build_darwin_arm64:
  <<: *build_definition
  variables:
    GOOS: darwin
    GOARCH: arm64

build_windows_amd64:
  <<: *build_definition
  variables:
    GOOS: windows
    GOARCH: amd64
    FILE_EXTENSION: .exe

build_windows_arm64:
  <<: *build_definition
  variables:
    GOOS: windows
    GOARCH: arm64
    FILE_EXTENSION: .exe

docker:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache docker-cli-buildx
    - docker login -u luiskugel -p $DOCKER_TOKEN
    - docker buildx create --use
    - docker buildx inspect --bootstrap
  script:
    - mkdir -p docker-bin
    - cp bin/eventsdb-linux-amd64 docker-bin/
    - cp bin/eventsdb-linux-arm64 docker-bin/
    - |
      docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg BINARY_AMD64=docker-bin/eventsdb-linux-amd64 \
        --build-arg BINARY_ARM64=docker-bin/eventsdb-linux-arm64 \
        -t $DOCKER_IMAGE:$DOCKER_TAG \
        -t $DOCKER_IMAGE:latest \
        --push \
        .
  dependencies:
    - build_linux_amd64
    - build_linux_arm64
  only:
    - main
    - tags

typescript-http-client:
  stage: build
  script:
    - cd client/typescript-http
    - npm install
    - npm run build
    # - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    # - npm publish --access public
    - echo $'@idot-digital:registry=https://git.idot-digital.com/api/v4/packages/npm/\n//git.idot-digital.com/api/v4/projects/104/packages/npm/:_authToken="${CI_JOB_TOKEN}"' > .npmrc
    - 'jq ''. + {"publishConfig": {"@idot-digital:registry": "https://git.idot-digital.com/api/v4/projects/104/packages/npm/"}}'' package.json > temp.json && mv temp.json package.json'
    - npm publish
  only:
    changes:
      - "client/typescript-http/**/*"
  except:
    - tags

typescript-grpc-client:
  stage: build
  script:
    - cd client/typescript-grpc
    - npm install
    - npm run build
    # - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    # - npm publish --access public
    - echo $'@idot-digital:registry=https://git.idot-digital.com/api/v4/packages/npm/\n//git.idot-digital.com/api/v4/projects/104/packages/npm/:_authToken="${CI_JOB_TOKEN}"' > .npmrc
    - 'jq ''. + {"publishConfig": {"@idot-digital:registry": "https://git.idot-digital.com/api/v4/projects/104/packages/npm/"}}'' package.json > temp.json && mv temp.json package.json'
    - npm publish
  only:
    changes:
      - "client/typescript-grpc/**/*"
  except:
    - tags

create_gitlab_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --description "Release created for $CI_COMMIT_TAG" \
        --assets-link "{\"name\":\"eventsdb-linux-amd64\",\"url\":\"https://git.idot-digital.com/idot-digital/tools/events-db/-/jobs/artifacts/v0.3/download?job=build_linux_amd64\"}" \
        --assets-link "{\"name\":\"eventsdb-linux-arm64\",\"url\":\"https://git.idot-digital.com/idot-digital/tools/events-db/-/jobs/artifacts/v0.3/download?job=build_linux_arm64\"}" \
        --assets-link "{\"name\":\"eventsdb-darwin-amd64\",\"url\":\"https://git.idot-digital.com/idot-digital/tools/events-db/-/jobs/artifacts/v0.3/download?job=build_darwin_amd64\"}" \
        --assets-link "{\"name\":\"eventsdb-darwin-arm64\",\"url\":\"https://git.idot-digital.com/idot-digital/tools/events-db/-/jobs/artifacts/v0.3/download?job=build_darwin_arm64\"}" \
        --assets-link "{\"name\":\"eventsdb-windows-amd64.exe\",\"url\":\"https://git.idot-digital.com/idot-digital/tools/events-db/-/jobs/artifacts/v0.3/download?job=build_windows_amd64\"}" \
        --assets-link "{\"name\":\"eventsdb-windows-arm64.exe\",\"url\":\"https://git.idot-digital.com/idot-digital/tools/events-db/-/jobs/artifacts/v0.3/download?job=build_windows_arm64\"}"
  dependencies:
    - build_linux_amd64
    - build_linux_arm64
    - build_darwin_amd64
    - build_darwin_arm64
    - build_windows_amd64
    - build_windows_arm64
  only:
    - tags

create_github_release:
  stage: release
  image: serversideup/github-cli:latest
  before_script:
    - echo $GITHUB_AUTH_TOKEN |gh auth login --with-token
  script:
    - |
      gh release create $CI_COMMIT_TAG \
        --title "Release $CI_COMMIT_TAG" \
        --notes "Release created for $CI_COMMIT_TAG" \
        --repo idot-digital/events-db \
        bin/eventsdb-linux-amd64 \
        bin/eventsdb-linux-arm64 \
        bin/eventsdb-darwin-amd64 \
        bin/eventsdb-darwin-arm64 \
        bin/eventsdb-windows-amd64.exe \
        bin/eventsdb-windows-arm64.exe
  dependencies:
    - build_linux_amd64
    - build_linux_arm64
    - build_darwin_amd64
    - build_darwin_arm64
    - build_windows_amd64
    - build_windows_arm64
  only:
    - tags
