image: golang:1.21

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  DOCKER_IMAGE: idotdigital/eventsdb
  DOCKER_TAG: ${CI_COMMIT_SHA}

stages:
  - build
  - docker
  - release

before_script:
  - mkdir -p $GOPATH/bin
  - export PATH=$GOPATH/bin:$PATH
  - go mod download

.build_template: &build_definition
  stage: build
  script:
    - mkdir -p bin
    - go build -o bin/eventsdb-$GOOS-$GOARCH cmd/eventsdb/main.go
  artifacts:
    paths:
      - bin/
    expire_in: 1 week

build_linux_amd64:
  <<: *build_definition
  variables:
    GOOS: linux
    GOARCH: amd64

build_linux_arm64:
  <<: *build_definition
  variables:
    GOOS: linux
    GOARCH: arm64

build_darwin_amd64:
  <<: *build_definition
  variables:
    GOOS: darwin
    GOARCH: amd64

build_darwin_arm64:
  <<: *build_definition
  variables:
    GOOS: darwin
    GOARCH: arm64

build_windows_amd64:
  <<: *build_definition
  variables:
    GOOS: windows
    GOARCH: amd64

build_windows_arm64:
  <<: *build_definition
  variables:
    GOOS: windows
    GOARCH: arm64

docker:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache docker-cli-buildx
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx inspect --bootstrap
  script:
    - |
      docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg BINARY_AMD64=bin/eventsdb-linux-amd64 \
        --build-arg BINARY_ARM64=bin/eventsdb-linux-arm64 \
        -t $DOCKER_IMAGE:$DOCKER_TAG \
        -t $DOCKER_IMAGE:latest \
        --push \
        .
  only:
    - main
    - tags

release:
  stage: release
  image: alpine:latest
  script:
    - |
      for os in linux darwin windows; do
        for arch in amd64 arm64; do
          if [ -f "bin/eventsdb-$os-$arch" ]; then
            tar -czf "eventsdb-$os-$arch.tar.gz" -C bin "eventsdb-$os-$arch"
          fi
        done
      done
  artifacts:
    paths:
      - "*.tar.gz"
    expire_in: 1 week
  only:
    - tags
