version: "3.8"

services:
  app:
    image: idotdigital/eventsdb:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=eventsdb
      - DB_PASSWORD=eventsdb
      - DB_NAME=eventsdb
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config:/app/config
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventsdb
      - MYSQL_USER=eventsdb
      - MYSQL_PASSWORD=eventsdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  mysql_data:
