CREATE TABLE `events` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `source` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data` VARBINARY(65535) NOT NULL
);